# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180412_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='blog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Blog', verbose_name='关联Blog信息'),
        ),
    ]
